# ========================= # Stage 1 → Build React App # =========================
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# ========================= # Stage 2 → Serve with Nginx # ========================= 
FROM nginx:alpine 
# Copy custom nginx config 
COPY nginx.conf /etc/nginx/conf.d/default.conf 

# Copy React build files 
COPY --from=build /app/dist /usr/share/nginx/html 

# Expose nginx port 
EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]