apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: team-project-manager-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "mysecretkey"
            - name: MONGO_URI
              value: "your_mongodb_connection_string"